### ISSUE TITLE
is it work for ci4?

### ISSUE THREAD

**Issue by sunkangchina** [scoumbourdis/image-crud#46]
looks dirs is for ci3.

thx

**Comment by scoumbourdis** [comment]
Hello @ttken ,

This is not working for now on CI4. I hope I will have an update on that.

Regards
Johnny

**Comment by sunkangchina** [comment]
Thank you

**Comment by scoumbourdis** [comment]
Hello @sunkangchina ,

I am glad to inform you that we now have Image CRUD for Codeigniter 4 

You can find it at the link: https://www.grocerycrud.com/image-crud-codeigniter-4

Enjoy :)

**Comment by sunkangchina** [comment]
thank you, 
i have using yii2cms for dev our projects. 
https://github.com/yii2cms/yii2cms
